vote:
  image: prantik/vote:master
  ports:
    - 5000:80
  links:
    - redis:redis

result:
  image: prantik/result:master
  ports:
    - 5001:4000
  links:
    - db:db

worker:
  image: prantik/worker:latest
  links:
    - redis:redis
    - db:db

redis:
  image: redis:alpine

db:
  image: postgres:9.4
