pipeline {
    agent any

    tools {
        maven 'maven 3.6.1'
    }

    stages {
        stage {
            stage("build") {
                steps {
                    echo "Compiling Worker App"
                    dir("worker") {
                        sh "mvn compile"
                    }                        
                }
            }
            stage("test") {
                steps {
                    echo "Running unit tests on worker app"
                }
            }
            stage("package") {
                steps {
                    echo "Packaging Worker App"
                }
            }
        }
    }

    post {
        always {
            echo "Building multibranch pipeline for worker is completed."
        }
    }
}